.TH tkeyboard
.SH NAME
tkeyboard \- a typing speed tester
.SH SYNOPSIS
.B tkeyboard
[\fB-w\fR \fIWORDS\fR]
[\fB-v\fR]
.SH DESCRIPTION
.B tkeyboard
generates a number of words for the user to enter in a row, after which provides a result in the form of typing speed (words per minute and characters per second). 
It only allows to enter the exact same string, but highlights with red if there's a mismatching symbol.
.SH OPTIONS
.TP
.BR \-w " " \fIWORDS\fR
Set the number of words to generate per attempt. Default is 20.
.TP
.BR \-v
Show version.
